### ISSUE TITLE
Install failed with Anaconda 3 - 

### ISSUE THREAD

**Issue by duytrung** [Blosc/bcolz#117]
I tried to install bcolz via pip install --upgrade. However, the installation failed. Here is the log:

C:\Anaconda3\Scripts>pip install bcolz --upgrade
Collecting bcolz from https://pypi.python.org/packages/source/b/bcolz/bcolz-0.7.3.tar.gz#md5=172c671
e14832e61bcae07afa9d41eff
  Downloading bcolz-0.7.3.tar.gz (518kB)
    100% |################################| 520kB 466kB/s ta 0:00:01
  In the tar file C:\Users\MYEXPE~1\AppData\Local\Temp\pip-nxouc0i7-unpack\bcolz-0.7.3.tar.gz the me
mber bcolz-0.7.3/LICENSES/ZLIB.txt is invalid: unable to resolve link inside archive
  In the tar file C:\Users\MYEXPE~1\AppData\Local\Temp\pip-nxouc0i7-unpack\bcolz-0.7.3.tar.gz the me
mber bcolz-0.7.3/LICENSES/LZ4.txt is invalid: unable to resolve link inside archive
  In the tar file C:\Users\MYEXPE~1\AppData\Local\Temp\pip-nxouc0i7-unpack\bcolz-0.7.3.tar.gz the me
mber bcolz-0.7.3/LICENSES/FASTLZ.txt is invalid: unable to resolve link inside archive
  In the tar file C:\Users\MYEXPE~1\AppData\Local\Temp\pip-nxouc0i7-unpack\bcolz-0.7.3.tar.gz the me
mber bcolz-0.7.3/LICENSES/STDINT.txt is invalid: unable to resolve link inside archive
  In the tar file C:\Users\MYEXPE~1\AppData\Local\Temp\pip-nxouc0i7-unpack\bcolz-0.7.3.tar.gz the me
mber bcolz-0.7.3/LICENSES/BLOSC.txt is invalid: unable to resolve link inside archive
  In the tar file C:\Users\MYEXPE~1\AppData\Local\Temp\pip-nxouc0i7-unpack\bcolz-0.7.3.tar.gz the me
mber bcolz-0.7.3/LICENSES/SNAPPY.txt is invalid: unable to resolve link inside archive
    * Found Cython 0.21.2 package installed.
    * Found numpy 1.9.1 package installed.
    * Found numexpr 2.3.1 package installed.
Installing collected packages: bcolz
  Found existing installation: bcolz 0.7.3.dev0
    Can't uninstall 'bcolz'. No files were found to uninstall.
  Running setup.py install for bcolz
    * Found Cython 0.21.2 package installed.
    * Found numpy 1.9.1 package installed.
    * Found numexpr 2.3.1 package installed.
    LLVM version 3.1svn, 3.1svn
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-fob278bi\bcolz\setup.py", line 236, in <m
odule>
        packages=['bcolz', 'bcolz.tests'],
      File "C:\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Anaconda3\lib\distutils\command\install.py", line 539, in run
        self.run_command('build')
      File "C:\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Anaconda3\lib\distutils\command\build.py", line 126, in run
        self.run_command(cmd_name)
      File "C:\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Anaconda3\lib\site-packages\Cython\Distutils\build_ext.py", line 163, in run
        _build_ext.build_ext.run(self)
      File "C:\Anaconda3\lib\distutils\command\build_ext.py", line 308, in run
        force=self.force)
      File "C:\Anaconda3\lib\site-packages\numpy\distutils\ccompiler.py", line 562, in new_compiler
        compiler = klass(None, dry_run, force)
      File "C:\Anaconda3\lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 57, in __init_
_
        verbose, dry_run, force)
      File "C:\Anaconda3\lib\distutils\cygwinccompiler.py", line 126, in __init__
        if self.ld_version >= "2.10.90":
    TypeError: unorderable types: NoneType() >= str()
    Complete output from command C:\Anaconda3\python.exe -c "import setuptools, tokenize;__file__='C
:\\Users\\MYEXPE~1\\AppData\\Local\\Temp\\pip-build-fob278bi\\bcolz\\setup.py';exec(compile(getattr(
tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record
 C:\Users\MYEXPE~1\AppData\Local\Temp\pip-ou0hn78_-record\install-record.txt --single-version-extern
ally-managed --compile:
    * Found Cython 0.21.2 package installed.

    * Found numpy 1.9.1 package installed.

    * Found numexpr 2.3.1 package installed.

    running install

    running build

    running build_py

    creating build

    creating build\lib.win-amd64-3.4

    creating build\lib.win-amd64-3.4\bcolz

    copying bcolz\arrayprint.py -> build\lib.win-amd64-3.4\bcolz

    copying bcolz\attrs.py -> build\lib.win-amd64-3.4\bcolz

    copying bcolz\chunked_eval.py -> build\lib.win-amd64-3.4\bcolz

    copying bcolz\ctable.py -> build\lib.win-amd64-3.4\bcolz

    copying bcolz\defaults.py -> build\lib.win-amd64-3.4\bcolz

    copying bcolz\py2help.py -> build\lib.win-amd64-3.4\bcolz

    copying bcolz\toplevel.py -> build\lib.win-amd64-3.4\bcolz

    copying bcolz\utils.py -> build\lib.win-amd64-3.4\bcolz

    copying bcolz\version.py -> build\lib.win-amd64-3.4\bcolz

    copying bcolz\__init__.py -> build\lib.win-amd64-3.4\bcolz

    creating build\lib.win-amd64-3.4\bcolz\tests

    copying bcolz\tests\all.py -> build\lib.win-amd64-3.4\bcolz\tests

    copying bcolz\tests\common.py -> build\lib.win-amd64-3.4\bcolz\tests

    copying bcolz\tests\test_attrs.py -> build\lib.win-amd64-3.4\bcolz\tests

    copying bcolz\tests\test_carray.py -> build\lib.win-amd64-3.4\bcolz\tests

    copying bcolz\tests\test_carray_objects.py -> build\lib.win-amd64-3.4\bcolz\tests

    copying bcolz\tests\test_ctable.py -> build\lib.win-amd64-3.4\bcolz\tests

    copying bcolz\tests\test_ndcarray.py -> build\lib.win-amd64-3.4\bcolz\tests

    copying bcolz\tests\test_queries.py -> build\lib.win-amd64-3.4\bcolz\tests

    copying bcolz\tests\__init__.py -> build\lib.win-amd64-3.4\bcolz\tests

    running build_ext

    LLVM version 3.1svn, 3.1svn

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-fob278bi\bcolz\setup.py", line 236, in <m
odule>

        packages=['bcolz', 'bcolz.tests'],

      File "C:\Anaconda3\lib\distutils\core.py", line 148, in setup

        dist.run_commands()

      File "C:\Anaconda3\lib\distutils\dist.py", line 955, in run_commands

        self.run_command(cmd)

      File "C:\Anaconda3\lib\distutils\dist.py", line 974, in run_command

        cmd_obj.run()

      File "C:\Anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run

        return orig.install.run(self)

      File "C:\Anaconda3\lib\distutils\command\install.py", line 539, in run

        self.run_command('build')

      File "C:\Anaconda3\lib\distutils\cmd.py", line 313, in run_command

        self.distribution.run_command(command)

      File "C:\Anaconda3\lib\distutils\dist.py", line 974, in run_command

        cmd_obj.run()

      File "C:\Anaconda3\lib\distutils\command\build.py", line 126, in run

        self.run_command(cmd_name)

      File "C:\Anaconda3\lib\distutils\cmd.py", line 313, in run_command

        self.distribution.run_command(command)

      File "C:\Anaconda3\lib\distutils\dist.py", line 974, in run_command

        cmd_obj.run()

      File "C:\Anaconda3\lib\site-packages\Cython\Distutils\build_ext.py", line 163, in run

        _build_ext.build_ext.run(self)

      File "C:\Anaconda3\lib\distutils\command\build_ext.py", line 308, in run

        force=self.force)

      File "C:\Anaconda3\lib\site-packages\numpy\distutils\ccompiler.py", line 562, in new_compiler

        compiler = klass(None, dry_run, force)

      File "C:\Anaconda3\lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 57, in __init_
_

        verbose, dry_run, force)

      File "C:\Anaconda3\lib\distutils\cygwinccompiler.py", line 126, in __init__

        if self.ld_version >= "2.10.90":

    TypeError: unorderable types: NoneType() >= str()

    ----------------------------------------
    Can't roll back bcolz; was not uninstalled
    Command "C:\Anaconda3\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\MYEXPE~1\\
AppData\\Local\\Temp\\pip-build-fob278bi\\bcolz\\setup.py';exec(compile(getattr(tokenize, 'open', op
en)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\MYEXPE~1\A
ppData\Local\Temp\pip-ou0hn78_-record\install-record.txt --single-version-externally-managed --compi
le" failed with error code 1 in C:\Users\MYEXPE~1\AppData\Local\Temp\pip-build-fob278bi\bcolz

Regards

**Comment by esc** [comment]
It seems to be an issue with the compiler. Since we currently have no way to automate checking every combination of windows, python and compiler, we can't guarantee it will work with every compiler.

Can you give me some more details about your system?

Anaconda version?
Python Version?
Windows version?
Compiler?
Command line? (Powershell, Git-BASH, Msys, ...)

**Comment by esc** [comment]
Also, the log you posted is a bit hard to read. I would suggest using tripple backticks to paste logs:

https://guides.github.com/features/mastering-markdown/

**Comment by esc** [comment]
Alternatively, it seems like there are a variety of bcolz binary builds available from the continuum anaconda repositories:

http://repo.continuum.io/pkgs/free/win-64/bcolz-0.7.3-np19py34_0.tar.bz2

Perhaps you can install bcolz using:

```
conda install bcolz
```

Please let us know if this worked for you.

**Comment by esc** [comment]
Another alternative might be to use the Windows binaries provided by Christoph Gohlke

www.lfd.uci.edu/~gohlke/pythonlibs/#bcolz

**Comment by esc** [comment]
Hi, any news on this one? If your problem has been solved, please feel free to close the issue.

**Comment by esc** [comment]
I am assuming this is no longer relevant or has been solved, feel free to re-open otherwise.
