### ISSUE TITLE
extracting rows from tables fails with np.object column

### ISSUE THREAD

**Issue by brentp** [Blosc/bcolz#179]
This code will demonstrate the error on master:

```
import bcolz
import numpy as np

dtype = np.dtype([("a", np.object),
                  ("b", np.uint8),
                  ("c", np.int32),
                  ("d", np.float32)
                  ])

a = bcolz.ctable(np.empty(0, dtype=dtype), mode="w")

a.append(("aaaaa", 23, 34567, 1.2355))
a.append(("aaaaa", 23, 34567, 1.2355))
a.append(("aaaaa", 23, 34567, 1.2355))
a.append(("aaaaa", 23, 34567, 1.2355))

print a[np.array([1, 0, 2])]
```

the error is:

```
Traceback (most recent call last):
  File "t.py", line 17, in <module>
    print a[np.array([1, 0, 2])]
  File "/install/data/anaconda/lib/python2.7/site-packages/bcolz/ctable.py", line 1087, in __getitem__
    return np.array([self[i] for i in key], dtype=self.dtype)
ValueError: Setting void-array with object members using buffer.
```

This fix is to change:
```
return np.array([self[i] for i in key], dtype=self.dtype)
```
to:
```
return np.array([tuple(self[i]) for i in key], dtype=self.dtype)
```
at the offending line in bcolz/ctable.py

**Comment by esc** [comment]
Please submit a pull-request with an appropriate commit that has a  test case that exposes the issue and another commit that fixes it. If you like also modify the changelog to include your fix.
