### ISSUE TITLE
Cannot install via pip

### ISSUE THREAD

**Issue by BrenBarn** [Blosc/bcolz#266]
Trying to install via `pip install bcolz` gives a long error ending with

```
raise ValueError("path '%s' cannot be absolute" % pathname)
ValueError: path '/tmp/bcolz/bcolz/carray_ext.pyx' cannot be absolute
```

The error is described in #250 (which is not really related).  This failure occurs on Windows (in my case, Win 7 64-bit); I don't know about other platforms.  I was able to install successfully by cloning the github repo and installing with `pip install -e`, so the problem seems to be with the release packaging and not the `setup.py` itself.

It seems other projects have had similar issues.  [Here](https://github.com/behave/behave/issues/28) is an issue on another project where they had the same "path cannot be absolute" error; it was apparently due to a misconfigured build environment when building the release.  It seems that somehow the `SOURCES.txt` file in the egg gets spurious locations added to it; in this case a location in `/tmp` is somehow added, which clearly seems wrong.

Whoever is building the PyPI releases should maybe check their setup to see what is getting into `SOURCES.txt` and why.

**Comment by FrancescAlted** [comment]
I am sorry but I am not seeing the `SOURCES.txt` anywhere in the tarball in PyPI.  In fact, I am not getting any error on my machine (Linux):

```
faltet@faltet-Latitude-E6430:~/uio/shyft-FA$ pip install bcolz
Collecting bcolz
  Downloading bcolz-0.11.3.tar.gz (582kB)
    100% |████████████████████████████████| 585kB 454kB/s 
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7 in /home/faltet/miniconda/lib/python2.7/site-packages (from bcolz)
Building wheels for collected packages: bcolz
  Running setup.py bdist_wheel for bcolz
  Stored in directory: /home/faltet/.cache/pip/wheels/80/4d/11/67e93ad4cb202e2eaa1145bd71be0a80fd244404ab5cc60963
Successfully built bcolz
Installing collected packages: bcolz
Successfully installed bcolz-0.11.3
```

Hmm, could you upgrade to newest setuptools *and* pip packages and retry?

**Comment by BrenBarn** [comment]
`SOURCES.txt` is inside the `bcolz.egg-info` directory in the tarball.

**Comment by BrenBarn** [comment]
I am already using the latest pip-installable pip (7.1.2) and setuptools (18.4).

**Comment by FrancescAlted** [comment]
Hmm, still not seeing it:

```
$ tar xvfz ~/Downloads/bcolz-0.11.3.tar.gz 
$ ls bcolz-0.11.3
ANNOUNCE.rst   bench         continuous-integration          makefile         README.rst         setup.py
appveyor.yml   bench_asv     coveralls_after_test_succes.sh  MANIFEST.in      RELEASE_NOTES.rst  subtree-merge-blosc.sh
asv.conf.json  c-blosc       doc                             pavement.py      RELEASING.rst      test_requirements.txt
bcolz          conda.recipe  LICENSES                        persistence.rst  requirements.txt   THANKS.rst
$ find bcolz-0.11.3 -name SOURCES.txt
$
```

**Comment by BrenBarn** [comment]
Do we have different files?  I just grabbed the one from [PyPI](https://pypi.python.org/pypi/bcolz/0.11.3) moments ago and it has an additional bcolz.egg-info directory in there.

**Comment by BrenBarn** [comment]
I notice that your pip says it's building a wheel and then doing `setup.py bdist_wheel` whereas mine is just doing `setup.py install`.

Here is the output for me:

```
> pip install bcolz
Collecting bcolz
  Using cached bcolz-0.11.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7 in c:\fakeprogs\python27\lib\site-packages (from bcolz)
Installing collected packages: bcolz
  Running setup.py install for bcolz
    Complete output from command C:\FakeProgs\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\brenbarn\\appdata\\local\\temp\\pip-build-5mlusf\\bcolz\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\brenbarn\appdata\local\temp\pip-clkazd-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\bcolz
    copying bcolz\arrayprint.py -> build\lib.win-amd64-2.7\bcolz
    copying bcolz\attrs.py -> build\lib.win-amd64-2.7\bcolz
    copying bcolz\chunked_eval.py -> build\lib.win-amd64-2.7\bcolz
    copying bcolz\ctable.py -> build\lib.win-amd64-2.7\bcolz
    copying bcolz\defaults.py -> build\lib.win-amd64-2.7\bcolz
    copying bcolz\py2help.py -> build\lib.win-amd64-2.7\bcolz
    copying bcolz\py2help_tests.py -> build\lib.win-amd64-2.7\bcolz
    copying bcolz\toplevel.py -> build\lib.win-amd64-2.7\bcolz
    copying bcolz\utils.py -> build\lib.win-amd64-2.7\bcolz
    copying bcolz\version.py -> build\lib.win-amd64-2.7\bcolz
    copying bcolz\__init__.py -> build\lib.win-amd64-2.7\bcolz
    creating build\lib.win-amd64-2.7\bench_asv
    copying bench_asv\arange.py -> build\lib.win-amd64-2.7\bench_asv
    copying bench_asv\bench_helper.py -> build\lib.win-amd64-2.7\bench_asv
    copying bench_asv\column_iter.py -> build\lib.win-amd64-2.7\bench_asv
    copying bench_asv\concat.py -> build\lib.win-amd64-2.7\bench_asv
    copying bench_asv\__init__.py -> build\lib.win-amd64-2.7\bench_asv
    creating build\lib.win-amd64-2.7\bcolz\tests
    copying bcolz\tests\all.py -> build\lib.win-amd64-2.7\bcolz\tests
    copying bcolz\tests\common.py -> build\lib.win-amd64-2.7\bcolz\tests
    copying bcolz\tests\test_attrs.py -> build\lib.win-amd64-2.7\bcolz\tests
    copying bcolz\tests\test_carray.py -> build\lib.win-amd64-2.7\bcolz\tests
    copying bcolz\tests\test_carray_objects.py -> build\lib.win-amd64-2.7\bcolz\tests
    copying bcolz\tests\test_ctable.py -> build\lib.win-amd64-2.7\bcolz\tests
    copying bcolz\tests\test_ndcarray.py -> build\lib.win-amd64-2.7\bcolz\tests
    copying bcolz\tests\test_queries.py -> build\lib.win-amd64-2.7\bcolz\tests
    copying bcolz\tests\__init__.py -> build\lib.win-amd64-2.7\bcolz\tests
    copying bcolz\carray_ext.pxd -> build\lib.win-amd64-2.7\bcolz
    running build_ext
    warning: manifest_maker: standard file '-c' not found

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\brenbarn\appdata\local\temp\pip-build-5mlusf\bcolz\setup.py", line 178, in <module>
        package_data={'bcolz': ['carray_ext.pxd']}
      File "C:\FakeProgs\Python27\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "C:\FakeProgs\Python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "C:\FakeProgs\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\FakeProgs\Python27\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\FakeProgs\Python27\lib\distutils\command\install.py", line 575, in run
        self.run_command(cmd_name)
      File "C:\FakeProgs\Python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\FakeProgs\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\FakeProgs\Python27\lib\site-packages\setuptools\command\install_egg_info.py", line 33, in run
        self.run_command('egg_info')
      File "C:\FakeProgs\Python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\FakeProgs\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\FakeProgs\Python27\lib\site-packages\setuptools\command\egg_info.py", line 180, in run
        self.find_sources()
      File "C:\FakeProgs\Python27\lib\site-packages\setuptools\command\egg_info.py", line 207, in find_sources
        mm.run()
      File "C:\FakeProgs\Python27\lib\site-packages\setuptools\command\egg_info.py", line 291, in run
        self.add_defaults()
      File "C:\FakeProgs\Python27\lib\site-packages\setuptools\command\egg_info.py", line 327, in add_defaults
        self.read_manifest()
      File "C:\FakeProgs\Python27\lib\site-packages\setuptools\command\sdist.py", line 196, in read_manifest
        self.filelist.append(line)
      File "C:\FakeProgs\Python27\lib\site-packages\setuptools\command\egg_info.py", line 232, in append
        path = convert_path(item)
      File "C:\FakeProgs\Python27\lib\distutils\util.py", line 124, in convert_path
        raise ValueError, "path '%s' cannot be absolute" % pathname
    ValueError: path '/tmp/bcolz/bcolz/carray_ext.pyx' cannot be absolute

    ----------------------------------------
Command "C:\FakeProgs\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\brenbarn\\appdata\\local\\temp\\pip-build-5mlusf\\bcolz\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\brenbarn\appdata\local\temp\pip-clkazd-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\brenbarn\appdata\local\temp\pip-build-5mlusf\bcolz
```

**Comment by FrancescAlted** [comment]
Oops, got it now!  I was using the tarball from github, not PyPI.  Tomorrow will try to fix that and release a new version.
