### ISSUE TITLE
bcolz installation fails when listed as dependency of project installed via setup.py develop or setup.py install

### ISSUE THREAD

**Issue by ssanderson** [Blosc/bcolz#277]
If I create a simple project with a setup.py like this:

```
from setuptools import setup
setup(
    name='foo',
    version='0.0.1',
    description='test',
    author='Me',
    author_email='me@me.me',
    py_modules='foo',
    install_requires='bcolz==0.10.0',
)
```
I can install successfully in development mode via `pip install -e .`.  If I install via `python setup.py develop`, however, I get a failure in the `bcolz` setup.py trying to tack an attribute onto `__builtins__`.

```
python setup.py develop
<lots of compiler messages>
creating /tmp/user/1000/easy_install-Li9Gh7/bcolz-0.10.0/.eggs/Cython-0.23.4-py2.7-linux-x86_64.egg
Extracting Cython-0.23.4-py2.7-linux-x86_64.egg to /tmp/user/1000/easy_install-Li9Gh7/bcolz-0.10.0/.eggs

Installed /tmp/user/1000/easy_install-Li9Gh7/bcolz-0.10.0/.eggs/Cython-0.23.4-py2.7-linux-x86_64.egg
* Found Cython 0.23.4 package installed.
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    install_requires='bcolz==0.10.0',
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/ssanderson/.virtualenvs/scratch/local/lib/python2.7/site-packages/setuptools/command/develop.py", line 32, in run
    self.install_for_development()
  File "/home/ssanderson/.virtualenvs/scratch/local/lib/python2.7/site-packages/setuptools/command/develop.py", line 132, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/home/ssanderson/.virtualenvs/scratch/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 709, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/ssanderson/.virtualenvs/scratch/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 836, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/home/ssanderson/.virtualenvs/scratch/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1081, in best_match
    return self.obtain(req, installer)
  File "/home/ssanderson/.virtualenvs/scratch/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1093, in obtain
    return installer(requirement)
  File "/home/ssanderson/.virtualenvs/scratch/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 629, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/ssanderson/.virtualenvs/scratch/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 659, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/ssanderson/.virtualenvs/scratch/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 842, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/ssanderson/.virtualenvs/scratch/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1070, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/ssanderson/.virtualenvs/scratch/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1056, in run_setup
    run_setup(setup_script, args)
  File "/home/ssanderson/.virtualenvs/scratch/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 240, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ssanderson/.virtualenvs/scratch/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ssanderson/.virtualenvs/scratch/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 164, in save_modules
    saved_exc.resume()
  File "/home/ssanderson/.virtualenvs/scratch/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 139, in resume
    compat.reraise(type, exc, self._tb)
  File "/home/ssanderson/.virtualenvs/scratch/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/home/ssanderson/.virtualenvs/scratch/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/home/ssanderson/.virtualenvs/scratch/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 237, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/home/ssanderson/.virtualenvs/scratch/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 267, in run
    return func()
  File "/home/ssanderson/.virtualenvs/scratch/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 236, in runner
    _execfile(setup_script, ns)
  File "/home/ssanderson/.virtualenvs/scratch/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/user/1000/easy_install-Li9Gh7/bcolz-0.10.0/setup.py", line 107, in <module>
    
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
```

The failure appears to be here: https://github.com/Blosc/bcolz/blob/master/setup.py#L29.  I'm not sure why `__builtins__` is a module in one context and a dict in another.

What does changing `__NUMPY_SETUP__` control?  Is there a straightforward way to work around this issue (either here or upstream)?

@richafrank @llllllllll this is the root cause of https://github.com/quantopian/zipline/issues/814

**Comment by ssanderson** [comment]
Numpy does this in their setup.py:

```
if sys.version_info[0] >= 3:
    import builtins
else:
    import __builtin__ as builtins
...
builtins.__NUMPY_SETUP__ = True
```

Note that they're manipulating `__builtin__`, not `__builtins__`, which leads me to believe that the line in `bcolz` setup.py is not actually accomplishing anything.

**Comment by FrancescAlted** [comment]
Yeah, this was recently added by @mindw, so perhaps he can shed more light on why this was needed.

**Comment by mindw** [comment]
I'll look into this with in a day or two.

**Comment by FrancescAlted** [comment]
@mindw ping?

**Comment by mindw** [comment]
looking into it

**Comment by ssanderson** [comment]
@FrancescAlted @mindw great!  Any idea when there will be a release with this change?
