### ISSUE TITLE
Does not install on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by lbeltrame** [Blosc/bcolz#309]
The error message is cryptic:

```
python2 setup.py build
SSE2 detected
Traceback (most recent call last):
  File "setup.py", line 228, in <module>
    cmdclass=LazyCommandClass(),
  File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 827, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1072, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1084, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 635, in easy_install
    not self.always_copy, self.local_index
  File "/usr/lib/python2.7/site-packages/setuptools/package_index.py", line 604, in fetch_distribution
    self.find_packages(requirement)
  File "/usr/lib/python2.7/site-packages/setuptools/package_index.py", line 441, in find_packages
    self.scan_url(self.index_url + requirement.unsafe_name+'/')
  File "/usr/lib/python2.7/site-packages/setuptools/package_index.py", line 775, in scan_url
    self.process_url(url, True)
  File "/usr/lib/python2.7/site-packages/setuptools/package_index.py", line 308, in process_url
    f = self.open_url(url, "Download error on %s: %%s -- Some packages may not be found!" % url)
  File "/usr/lib/python2.7/site-packages/setuptools/package_index.py", line 714, in open_url
    return open_with_auth(url, self.opener)
  File "/usr/lib/python2.7/site-packages/setuptools/package_index.py", line 909, in _socket_timeout
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/setuptools/package_index.py", line 1023, in open_with_auth
    fp = opener(request)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/site-packages/setuptools/ssl_support.py", line 158, in https_open
    lambda host, **kw: VerifyingHTTPSConn(host, self.ca_bundle, **kw), req
  File "/usr/lib64/python2.7/urllib2.py", line 1194, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/usr/lib/python2.7/site-packages/setuptools/ssl_support.py", line 186, in connect
    sock, cert_reqs=ssl.CERT_REQUIRED, ca_certs=self.ca_bundle
  File "/usr/lib64/python2.7/ssl.py", line 919, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib64/python2.7/ssl.py", line 526, in __init__
    self._context.load_verify_locations(cafile=cafile, capath=capath)
IOError: [Errno 2] No such file or directory
```

**Comment by FrancescAlted** [comment]
Hmm, I can't reproduce this on my machine.  Judging from the error, it seems to me that you have problems in your Python installation (SSL-related, apparently).  Please try getting help in a Python forum and feel free to re-open this issue if necessary.

**Comment by lbeltrame** [comment]
The reason was the lack of setuptools_scm, which failed to download and caused the SSL error, which is totally unrelated.

**Comment by FrancescAlted** [comment]
Ok.  Not trivial to determine the root of the problem.  Thanks for reporting.
