### ISSUE TITLE
test_leftover_ptr_with_statement_create_open fails on s390x, powerpc

### ISSUE THREAD

**Issue by danstender** [Blosc/bcolz#329]
Hi,
we have a test failure here on s390x and the powerpc ports [1]:
```
======================================================================
FAIL: test_leftover_ptr_create_flush_open (bcolz.tests.test_carray.LeftoverDiskTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "bcolz/tests/test_carray.py", line 2516, in test_leftover_ptr_create_flush_open
    self.assertEqual((n_chunks * chunklen) + i, out.value)
AssertionError: 100 != 0

======================================================================
FAIL: test_leftover_ptr_with_statement_create_open (bcolz.tests.test_carray.LeftoverDiskTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "bcolz/tests/test_carray.py", line 2533, in test_leftover_ptr_with_statement_create_open
    self.assertEqual((n_chunks * chunklen) + i, out.value)
AssertionError: 100 != 0

----------------------------------------------------------------------
Ran 1254 tests in 5.247s

FAILED (failures=2, skipped=156)
```
Could this be fixed somehow?

[1] https://buildd.debian.org/status/package.php?p=bcolz&suite=experimental

**Comment by FrancescAlted** [comment]
Nope,  bee8b1e is not a proper fix.  I have access to a POWER8 machine (Big Endian), and tests are not passing.  Probably this needs more consideration.

**Comment by danstender** [comment]
O.k., no problem. I could exclude the BEs from building within Debian, and also reactivate them when they are going to be supported in the future. The majority of officially supported archs are supported, so this isn't that bad. Thanks for working on this anyway.
