### ISSUE TITLE
get exception when import bcolz when my git is return non-zero exit.

### ISSUE THREAD

**Issue by WoolenWang** [Blosc/bcolz#403]
```python
Command '['git', 'describe']' returned non-zero exit status 128.
Traceback (most recent call last):
  File "E:\git\py_help\py_help\api_help\flask\__init__.py", line 95, in dynamic_load_with_module
    the_mod = importlib.import_module(total_model_name)
    │         │                       └ 'woolen_quant.controllers.socket.v1.data.k_data'
    │         └ <module 'importlib' from 'D:\\running\\python37_x64\\lib\\importlib\\__init__.py'>
    └ <module 'woolen_quant.controllers.socket.v1.ctrl.terminal' from 'E:\\git\\wquant\\wquant\\woolen_quant\\controllers\\socket\\v1\...
  File "D:\running\python37_x64\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │                      │    │        │        └ 0
           │                      │    │        └ None
           │                      │    └ 0
           │                      └ 'woolen_quant.controllers.socket.v1.data.k_data'
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\git\wquant\wquant\woolen_quant\controllers\socket\v1\data\k_data.py", line 4, in <module>
    from woolen_quant.models.rqalpha.rqalpha_proxy import RqalphaDataProxy
  File "E:\git\wquant\wquant\woolen_quant\models\rqalpha\rqalpha_proxy.py", line 11, in <module>
    from rqalpha.data.base_data_source import BaseDataSource
  File "D:\running\python37_x64\lib\site-packages\rqalpha\data\base_data_source.py", line 33, in <module>
    from rqalpha.data.daybar_store import DayBarStore
  File "D:\running\python37_x64\lib\site-packages\rqalpha\data\daybar_store.py", line 19, in <module>
    import bcolz
  File "D:\running\python37_x64\lib\site-packages\bcolz\__init__.py", line 124, in <module>
    git_description = _get_git_description(__path__[0])
                      │                    └ ['D:\\running\\python37_x64\\lib\\site-packages\\bcolz']
                      └ <function _get_git_description at 0x000001F923D21D38>
  File "D:\running\python37_x64\lib\site-packages\bcolz\__init__.py", line 117, in _get_git_description
    stderr=subprocess.STDOUT).strip()
  File "D:\running\python37_x64\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "D:\running\python37_x64\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'describe']' returned non-zero exit status 128.
```
system is windows 10, python3.7 x64.
please except all the exception in checkoutput .

**Comment by WoolenWang** [comment]
have the same issue
